apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pc-volume-claim
  labels:
    app: mariadb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi