services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/stinger/server/data/:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - mariadb-network
    restart:
      unless-stopped

  servicereg:
    image: stinger22/servicereg
    container_name: servicereg
    hostname: servicereg
    expose:
      - 8761
    ports:
      - 8761:8761
    depends_on:
      - mariadb
    networks:
      - mariadb-network
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  userms:
    image: stinger22/userms
    container_name: userms
    depends_on:
      - servicereg
    expose:
      - 8081
    networks:
      - mariadb-network
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

  imagems:
    image: stinger22/imagems
    container_name: image
    depends_on:
      - servicereg
    expose:
      - 8082
    networks:
      - mariadb-network
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  storagems:
    image: stinger22/storagems
    container_name: storagems
    depends_on:
      - servicereg
    volumes:
      - /home/stinger/server/storage/:/storage/
    expose:
      - 8084
    networks:
      - mariadb-network
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka
      - spring.servlet.multipart.max-file-size=10MB
      - spring.servlet.multipart.max-request-size=10MB

  gateway-ms:
    image: stinger22/gateway-ms
    container_name: gateway
    ports:
      - 8080:8080
    depends_on:
      - servicereg
    networks:
      - mariadb-network
      - microservice-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://servicereg:8761/eureka

networks:
  mariadb-network:
    driver: bridge
  microservice-network:
    driver: bridge